baseURL = 'https://simonsure.com'
languageCode = "en"
defaultContentLanguage = "en"
title = 'Simon Sure'
theme = 'simonsure.com-theme'
enableEmoji = true

[params]
author = "Simon Sure"
description = "Simon Sure's Personal Website"
keywords = "student,intern,nvidia,optiver,princeton,writing,reading,coding,learning,teaching,developer,founder,technology,ethz,eth,zurich,computer science"
info = ["CS @ETHZurich, Former CS @PrincetonUniversity", "Dev @Palantir, Former Systems @NVIDIA, Former SWE @Optiver", "Builder, Tech Enthusiast, Thinker"]
avatarURL = "portraits/profile.jpg"
since = 2022
colorScheme = "auto"
math = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa-2x fa-brands fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/simon-sure/"

[[params.social]]
name = "Substack"
icon = "fa-2x fa-solid fa-inbox"
weight = 2
url = "https://simonsure.substack.com/"

[[params.social]]
name = "X/Twitter"
icon = "fa-2x fa-brands fa-x-twitter"
weight = 3
url = "https://twitter.com/rold_si"

# [[params.social]]
# name = "Mastodon"
# icon = "fa fa-2x fa-brands fa-mastodon"
# rel = "me"
# weight = 3
# url = "https://mastodon.social/@simonsure"

# [[params.social]]
# name = "Bluesky"
# #icon = "fa fa-2x fa-brands fa-mastodon"
# bluesky = " "
# weight = 4
# url = "https://bsky.app/profile/simonsure.com"

# [[params.social]]
# name = "Threads"
# icon = "fa fa-2x fa-brands fa-threads"
# weight = 5
# url = "https://www.threads.net/@rold_si"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-brands fa-instagram"
weight = 6
url = "https://www.instagram.com/rold_si/"

# [[params.social]]
# name = "YouTube"
# icon = "fa fa-2x fa-brands fa-youtube"
# weight = 7
# url = "https://www.youtube.com/@rold_si"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-brands fa-github"
weight = 8
url = "https://github.com/RoldSI/"

[[menu.main]]
name = "Posts"
weight = 1
url = "https://simonsure.substack.com/"

[[menu.main]]
name = "Resume"
weight = 2

# [[menu.main]]
# name = "About"
# weight = 3
# url = "https://simonsure.substack.com/about"

[[menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
