baseURL = 'https://simonsure.com'
languageCode = "en"
defaultContentLanguage = "en"
title = 'Simon Sure'
theme = 'hugo-coder'
enableEmoji = true
googleAnalytics = "G-K9QXMKQWG7"

[params]
author = "Simon Sure"
description = "Simon Sure's Personal Website"
keywords = "student,intern,nvidia,optiver,princeton,writing,reading,coding,learning,teaching,developer,founder,technology,ethz,eth,zurich,computer science"
info = ["Systems Intern @NVIDIA, Incoming SWE Intern @Optiver, TA @ETHZurich", "CS Student @ETHZurich, Upcoming Exchange Student @PrincetonUniversity", "Tech Enthusiast, Thinker"]
avatarURL = "portraits/profile.png"
since = 2022
colorScheme = "auto"
math = true

[params.googleTagManager]
id = "G-K9QXMKQWG7"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa-2x fa-brands fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/simon-sure/"

[[params.social]]
name = "X/Twitter"
icon = "fa-2x fa-brands fa-x-twitter"
weight = 2
url = "https://twitter.com/rold_si"

[[params.social]]
name = "Mastodon"
icon = "fa fa-2x fa-brands fa-mastodon"
rel = "me"
weight = 3
url = "https://mastodon.social/@simonsure"

[[params.social]]
name = "Bluesky"
#icon = "fa fa-2x fa-brands fa-mastodon"
bluesky = " "
weight = 4
url = "https://bsky.app/profile/simonsure.com"

[[params.social]]
name = "Threads"
icon = "fa fa-2x fa-brands fa-threads"
weight = 5
url = "https://www.threads.net/@rold_si"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-brands fa-instagram"
weight = 6
url = "https://www.instagram.com/rold_si/"

[[params.social]]
name = "YouTube"
icon = "fa fa-2x fa-brands fa-youtube"
weight = 7
url = "https://www.youtube.com/@rold_si"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-brands fa-github"
weight = 8
url = "https://github.com/RoldSI/"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Resume"
weight = 2
url = "/simon_sure_resume.pdf"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "ETHZ"
weight = 4
url = "ethz/"

[[menu.main]]
name = "Posts"
weight = 5
url = "posts/"

[[menu.main]]
name = "Reading"
weight = 6
url = "reading"

[[menu.main]]
name = "Contact"
weight = 7
url = "contact/"
